version: '3.8'

services:

  php-apache:
    build: .
    container_name: canteen_web
    volumes:
      - ./:/var/www/html/
    ports:
      - "7000:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: canteen_db
    restart: always
    environment:
      MYSQL_DATABASE: Canteen_Management_System
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/Canteen_Management_System.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: canteen_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: canteen_db     # connect to MySQL container name
      PMA_USER: root
      PMA_PASSWORD: ""         # empty root password
      PMA_ARBITRARY: 1         # allows manual host entry if needed
    depends_on:
      - db

volumes:
  db_data:
